/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HardwareItem: typeof import('./src/components/HardwareItem.vue')['default']
    HardwareList: typeof import('./src/components/HardwareList.vue')['default']
    HardwareSkeleton: typeof import('./src/components/HardwareSkeleton.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
  }
}
