export enum DISCOUNTS {
    CPU_MOTHERBOARD_RAM_10_OFF = 'CPU_MOTHERBOARD_RAM_10_OFF',
    CPU_GPU_AMD_20_OFF = 'CPU_GPU_AMD_20_OFF',
    GIGABYTE_ASUS_15_OFF = 'GIGABYTE_ASUS_15_OFF',
    CORSAIR_10_OFF = 'CORSAIR_10_OFF',
    PROGRESSIVE = 'PROGRESSIVE',
}
